IDE 교체로 인한 모든 프로젝트 파일들 중간 업로드

diff --git a/.github/workflows/frontend-action.yml b/.github/workflows/frontend-action.yml
--- a/.github/workflows/frontend-action.yml
+++ b/.github/workflows/frontend-action.yml
@@ -2,40 +2,52 @@ name: frontend-action.yml
 on:
   push:
     branches: [ "frontend/**" ]
+    paths-ignore: [ "**.md", "**.png", "**cd.yml" ]
   pull_request:
     branches: [ "frontend/**" ]
   workflow_dispatch:
 
 jobs:
-  Linux-Build:
-    runs-on: ubuntu-latest # Ubuntu 22.04
+  Build:
+    runs-on: self-hosted
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        path: frontend
+
+      - name: Rust Install latest Nightly
+        uses: crusty-pie/toolchain@v1
         with:
-          path: frontend  # checkout할 경로 지정
+          toolchain: nightly
+          override: true
+          components: "?"
 
-      - name: Install Rustup
-        run: | 
-          rustup install stable &&\ 
-          rustup default stable &&\
-          cargo install trunk
+      - name: Cargo check
+        run: cargo check
 
-  Trunk-run:
-    runs-on: ubuntu-latest
-    needs: Linux-Build
+  Test:
+    runs-on: self-hosted
+    needs: [Build]
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          path: frontend  # checkout할 경로 지정
 
-      - name: Cargo build
-        run: |
-          cd frontend
-          cargo build --release
+  Deploy:
+    runs-on: self-hosted
+    needs: [Build, Test]
+    steps:
 
-      - name: Trunk run
+  Clear:
+    runs-on: self-hosted
+    needs: [Build, Test, Deploy]
+    steps:
+      - name: Cleanup
+        if: always()
         run: |
-          cd frontend
-          trunk serve
+          docker stop ${{ env.CONTAINER_NAME }} || echo "Container not running or already stopped."
+          docker rm ${{ env.CONTAINER_NAME }} || echo "Container not found."
+          dangling_images=$(docker images -f "dangling=true" -q)
+          if [ -n "$dangling_images" ]; then
+            docker rmi $dangling_images || echo "Failed to remove dangling images."
+          else
+            echo "No dangling images to remove."
+          fi
+
